server:
  port: 8082
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
      
      
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
           '[**]':
              allowedOrigins: "*"
              allowedHeaders: "*"
              allowedMethods: "*"
      routes:
        - id: userModule
          uri: http://localhost:8084/
          predicates:
            - Path=/auth/**,/api/v1/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: companyModule
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1.0/market/**